### PR TITLE
Add smoke tests

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR adds smoke tests for some common scenarios.

The goal of the smoke tests is to increase confidence that the Docker image that is produced works as 
intended.
The repo contains other tests, which are great, but what this PR adds is that it runs an integration 
test using the following setup:

1. Build the Docker image
2. Run the Docker image with the `tests` directory mapped into the container
3. Run the Docker image's normal entrypoint (`bin/run.sh`) on each of the test cases defined in the 
`tests` directory
4. Verify that the output of those test runs matches the expected output (which is stored inside the 
`tests` directories

If successful, we then know that:

1. The Docker image can be built successfully
2. The `bin/run.sh` entrypoint inside the Docker image is setup correctly
3. The test runner generates the correct output

### CODE REVIEW

**Comment by iHiD** [comment]
(This is red btw, @ErikSchierboom)

**Comment by verdammelt** [comment]
Should we replace the lisp test files used with something minimal?

As for expected behavior - what is the expected behavior of the 'empty file'. The behavior captured here is not because an empty file is itself bad - but because the empty file does not define any of the symbols that the test file expect to have been defined.

**Comment by ErikSchierboom** [comment]
> Should we replace the lisp test files used with something minimal?

Maybe in a follow up PR? This was just an easy way to get the required test cases

**Comment by ErikSchierboom** [comment]
> As for expected behavior - what is the expected behavior of the 'empty file'. The behavior captured here is not because an empty file is itself bad - but because the empty file does not define any of the symbols that the test file expect to have been defined.

It is a standard test case as some tracks have issues dealing with empty files.

**Comment by ErikSchierboom** [comment]
@verdammelt Are you happy enough with this PR or would you like to do the simplification first?

**Review by verdammelt — APPROVED** [review]

**Comment by verdammelt** [comment]
> @verdammelt Are you happy enough with this PR or would you like to do the simplification first?

Happy enough, merge when you want...

**Pull request merged**
