### PR TITLE
[DRAFT] Refactor Dockerfile to have a multi-step build.

### PR DESCRIPTION
**Pull request by verdammelt**
First we want to build a SBCL which has quicklisp and our dependencies
installed. This is handled by `bootstrap.sh`.

Next we want to build the test runner which is built by the builder of
the previous step and loads up our test runner source code.

Finally we create a fresh image which only includes quicklisp files
and cache, the test runner and the `run.sh` script.

### CODE REVIEW

**Comment by verdammelt** [comment]
I believe that since this includes a Dockerfile change I will need the review of the ops team. But first I'd like review of others on the common lisp team. So I'll mark this as draft for now.

**Comment by TheLostLambda** [comment]
Hmm, I've given it a bit of a look over this morning and had a couple of questions. First, I figure I should get the motivation for the change. While this refactoring still generates a functional test runner, it generates two images, both of which are larger than the original image. The final image is now ~95MB compared to the original ~50MB. This seems to be because we are using a base image with SBCL already packaged, so moving to regular Alpine brings things back down to the original ~50MB.

Additionally, when I was playing around with this version, I got stuck in the debugger at one point. Starting with the `--script` tag disables a lot of SBCL cruft and turns off the interactive traps like that. We would need to do something similar for this I think.

Overall, I think there are some really good things here that we should merge upstream (the setting of SBCL's home directory is an especially good idea!), but it feels a little bit like adding complexity without too much gain. It's possible, however, that I'm just missing the motivation for this change.

**Comment by verdammelt** [comment]
You have very good points. As for motivation of these changes I fear it might be too much of me 'playing around' and not enough 'good reason' :)

But I think there were some reasons behind my playing around - let me try to enumerate them and then we can figure out which are worth making changes for .

* Since Dockerfile changes need 'external' review by the ops team I wanted to remove as much as I could from the file. The Dockerfile currently contains implementation details such as the list of dependencies and the name and location of the source code
* When reading up about Dockerfiles I was reminded that it is "Best/Recommended Practice"(TM) to have the final image contain only what is needed - so I wanted to break the file into a builder image and a runner image
* I thought (and I could be wrong) that by splitting out some steps then due to caching only the steps which depend on changed files will be rebuilt. For example in my version if quicklisp is not changed then the builder executable will not be created again. And if `run.lisp` changes then only the building of the test runner and subsequent steps will be recreated.
* I wanted to separate the code from the knowledge of the environment it ran in. That way if one wanted one could load run.lisp into a REPL and use it to run tests locally. (In fact I sort of want to make a ASDF system definition for it so that I could do it if I wanted...)

If we decide any of those are useful then I can create PR(s) which address those issues.
If we decide that none of these are useful that is OK as well - I did learn a few things along the way so I feel OK about that.

**Comment by TheLostLambda** [comment]
I think that, overall, those are some very good motivations. Addressing them in the order presented:

- I certainly agree that it would be good to minimize the amount of review required by external parties like the DevOps team, but I feel the spirit of that is so that the DevOps team can keep an eye on the sort of things installed in an image. I suppose that we would have to ask them, but I think they would want to review scripts called in the Dockerfile as well. That's just my guess at their intent though, so I'm not sure how to best deal with this.

**Comment by verdammelt** [comment]
OK, I think I'll close this PR and (possibly).

**Pull request closed without merging**
